### PR TITLE
Problem with css code for overriding #760

### PR DESCRIPTION
**Pull request by ppetkow**
- There is a lot of changes on css files, but this request affect and 2 js file for modal setting and change GULP configuration to support scss compilation. 
- The naming and file structure in dist folder is same.
- I keep all visual styling of app. 
- Move all colors to variables for 3th part easy overriding 
- Remove some !important properties

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @ppetkow , this looks really good! I'm really glad with your effort to pick this up, it's a great improvement. And sorry for my late reply, it's holiday season.

Some feedbacks:

1. great that you pulled out colors and styling into `styles.scss`!
2. shouldn't `jsoneditor.scss` and all others import `styles.scss` instead of the other way around? `jsoneditor.scss` depends on `styles.scss` and not the other way around right?
3. I noticed one small glitch: the text color of the search result summary left from the search box (like "5 results") should be white but is black.
4. My fingers are itching to refactor the main structure (menu, nav bar, contents, errors, status bar) with flexbox but probably better to address that later, the PR is already quite large.

**Comment by ppetkow** [comment]
No problem for speed :) Im on work :D I will check this points and make new commit. 

Yep number 4 is for next PR maybe ;)

**Comment by josdejong** [comment]
Your latest changes looks good :+1: will merge your work now.

**Comment by josdejong** [comment]
@ppetkow FYI: you're SASS implementation is now published in `v6.4.0` (the improved search box too). Thanks again :)

**Pull request merged**
