### PR TITLE
#382 Read only text mode.

### PR DESCRIPTION
**Pull request by walkerrandolphsmith**
Addresses [#382](https://github.com/josdejong/jsoneditor/issues/382). I have also added an example file in addition to the changes in `./src`. I didn't want to make the surface area of `options` any larger, so I decided to use `onEditable` to determine if the textarea in `text` mode is editable. If the `onEditable` key is absent in the `options` than the content is editable. If the key is present and has a value that is a function, it will determine whether the text area is editable based on the result of `onEditable`'s invocation.

If hijacking the `onEditable` option is not appropriate I'd love to chat about the desired api of `options`.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Walker, looks good!

Two remarks:
- It would be nice if we could make the editor readonly when in mode `code` too
- Thanks for adding an example too. Can you rename it to `09_readonly_text_mode.html`?

**Comment by josdejong** [comment]
> If hijacking the onEditable option is not appropriate I'd love to chat about the desired api of options.

I agree with you, using `onEditable` for making the text mode readonly feels a bit like misusing the existing option. On the other hand it keeps the API compact and consistent. I think your solution is elegant.

**Comment by walkerrandolphsmith** [comment]
Okay, I can take a look into supporting read only `code` modes. I can rename the example file. I am surprised I didn't notice the convention!

**Comment by walkerrandolphsmith** [comment]
So that should allow the `code` mode to be configured to be read only as well.

There was a moment where I could't decide which styling was most appropriate:

```
aceEditor.setOptions({ readOnly: isReadOnly });
```

```
aceEditor.setOptions({readOnly: isReadOnly});
```

```
aceEditor.setOptions({
    readOnly: isReadOnly
});
```

Would you be interested in adding lint rules and [eslint](http://eslint.org/) to enforce style guides outlined in the [contributing](https://github.com/josdejong/jsoneditor/blob/master/CONTRIBUTING.md) doc? I can spin off a new feature and associated PR.

**Comment by walkerrandolphsmith** [comment]
Rebased the upstream develop branch.

**Comment by josdejong** [comment]
Thanks, looks good! 

Reminder to myself: add a sentence about that you can use `onEditable` for modes `text` and `code` too in the docs.

**Comment by josdejong** [comment]
As for the styling: I tend to use the styling you used in the PR too lately. A linter would be welcome! Would be nice if you could set that up that for jsoneditor, thanks beforehand.

**Pull request merged**
