### PR TITLE
Create option to hide the blue main menu bar on top 

### LINKED ISSUE #581: Create option to hide the blue main menu bar on top
```
var editor = new JSONEditor(dom, {
                            mode: 'code',
                            navigationBar: false,
                            statusBar: false,
                        });

```
statusBar is hidden, but navigationBar isn't.

image

### PR DESCRIPTION
**Pull request by tanmayrajani**
Fixes #581 

- also contains some typo corrections, JSDoc corrections etc.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @tanmayrajani, your PR looks good! Thanks for all the little code corrections too :)

Two remarks:

1. In textmode.js, I think it would be neat to move the code to create the `var poweredBy = ...` inside the first `if (this.options.mainMenuBar) {...}` block so there is only one such block instead of two.

2. When disabling the `mainMenuBar`, the contents of the editor do not fill up the whole container: at the bottom, there is space left with the height of the main menu. There is some CSS involved here (top padding and margin). This is from before the time we have `display: flex` ;) Can you look into that?

**Comment by tanmayrajani** [comment]
Thanks for the review, @josdejong! I'll work on these changes soon. Having a bit busy week :)

**Comment by tanmayrajani** [comment]
Sorry for the delay, I've pushed my changes in above commit. Let me know if I missed something, it's a big changes so it's quite possible. I've tested the CSS changes against all modes, with and without `mainMenuBar`, `statusBar` and `navigationBar`.

**Comment by josdejong** [comment]
Thanks Tanmay, I hope to test your latest changes tomorrow.

**Comment by josdejong** [comment]
I've tested `mainMenuBar` extensively, with different modes and combinations of `navigationBar` and `statusBar`, and all works like a charm, thanks again @tanmayrajani !

**Comment by josdejong** [comment]
The new option `mainMenuBar` is now available in `jsoneditor@5.26.0`

**Pull request merged**
