### PR TITLE
spanish translate

### PR DESCRIPTION
**Pull request by joabac**
spanish translate ,  UI texts

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for creating a Spanish translation @joabac 👍 

I see you've created multiple PR's (#1303, #1304, #1305, and this one), can you close all but one please? Which one is the one that should be merged?

**Comment by joabac** [comment]
you're very welcome, the correct is: spanish translate #1306.
The others were closed . 
sorry for the mistakes the indentations are very strict.

best regards!

**Comment by josdejong** [comment]
Thanks for your work Joaquin! 

For your information: you can update an existing PR with extra commits to correct any mistakes, there is no need to create a new PR with every change. To check for indentation issues, you can run `npm run lint`.

**Comment by josdejong** [comment]
Spanish language support is now available in `v9.4.0`

**Pull request merged**
