### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by rgarrigue**
Hi @josdejong 

I like JSONEditor, and since I like self hosting my tools too, here's a Dockerfile I made. It works like this

```bash
docker build -t local/jsoneditor:test .
docker run --name test -p80:80 -d local/jsoneditor:test
# open localhost:80 in your browser
docker rm -f test
```

I guess this could be added somewhere in the documentation.

The `misc/index.html` is a c/c of the README's example with a <title>. The result is bad, I hope you can provide a better one, a bit like the official jsoneditor website ?

Last but not least, I can provide a github action to build & push this into docker hub for an official image. Except you'ld need and official repository, getting one for FOSS project is quite easy. So if you're interested, tell me, I'll add it to the PR

Fare well :-)

### CODE REVIEW

**Comment by josdejong** [comment]
This is an interesting idea Rémy, thanks! 

It would be more neat indeed to give the editor a full page size instead of 400x400 px (that's easy to adjust).

Thinking aloud here: as long as this is just a single Dockerfile and index.html file it could be part of this repo, but as soon as you want to do do steps like push an image to docker hub etc, it is probably better to do that in a separate repo so both repo's can focus on one thing. So we could set up a repo `jsoneditor-docker` or `docker-jsoneditor` or something like that and take it from there. What do you think?

**Comment by josdejong** [comment]
Why would it be easier from this repo `jsoneditor` vs a separate repo like `jsoneditor-docker`? I suppose in both cases it is a single `npm install ...` and then a docker build?

**Comment by rgarrigue** [comment]
Let's say you put the Dockerfile in a separate repository. If the CI is there too like Github Action or Docker Hub integratin, how do you know in this context when a tag is made here ? You don't. So what, a cron ? Costly if possible. I'ld say it's an enterprise solution, when you have a generic way of doing thing with a standard Dockerfile for most of your react app, provided they follow the enterprise good practice, etc.

Solution n°2, you put the CI definition hence triggering here. Half baked since you've the CI part of the docker thing here, and the rest in the separate repository. But it's able to trigger on a tag event basis, good. But what will you do then, checkout the separate repository to grab your dockerfile & assets. More scripting just to separate the Dockerfile & asset ? Drifting far from KISS here for no good reason.

Again, it's just my opinion. Your app, your choice.

**Comment by josdejong** [comment]
Ah, so you're thinking about how to automate publishing a new version to Docker Hub when there is a new version of mathjs, I get it.

I'm not really sure, but it _may_ be not that hard to do in a separate repo: To keep a dependency up to date, you can use for example https://dependabot.com/. This automatically creates a PR when there is a new version of a dependency, which you can merge with one click. I can imagine that after merging, you can automatically run a Github Action which will publish a new version to Docker Hub.

The reason I'm a bit hesitant to add docker related stuff to the repository boils down to the single-responsibility principle. I suppose the integration to publish to Docker Hub requires adding some dependencies to the library, which bloat the library. And this year it's Docker, next year it's Kubernetes, or platform X and environment Y.

At this point the Docker Hub integration feels quite niche, though I understand it can be very nice to have. I have a preference to put the Docker integration in a separate repo. If Docker turns out to be a major solution for a lot of people, we can always reconsider integrating it in the `josdejong/jsoneditor` repo if that would be helpful.

**Comment by rgarrigue** [comment]
Hi @josdejong. I'm cleaning up my stale PRs list. What about this one ? If you decide to add it here it'll need fixes on the index.html, otherwise you can close it and c/c the Dockerfile to a docker dedicated one whenever you feel like

**Comment by josdejong** [comment]
Thanks for getting back Rémy.

I prefer creating a separate repository like say `jsoneditor-docker` for this to keep the current repo focused. Thanks again for your idea and PR though! I'll close this PR now.

**Pull request closed without merging**
