### PR TITLE
Made onChange execute after debounced validation and added function to get valication errors.

### PR DESCRIPTION
**Pull request by ChrisAcrobat**
Added #1072

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for your PR Christoffer!

I think this PR contains two ideas:

1. Implement a method `getValidationErrors`.
2. Change `onChange` such that it triggers after the debounced JSON schema validation did run. 

I like the new method `getValidationErrors`, that makes a lot of sense. I have doubts about the changes in `onChange`. The callback `onChange` fires when the JSON contents changes. This is independent of changes in the JSON Schema validation, which can be captured with `onValidationError`.  Running JSON Schema validation is run debounced for performance reasons, so there is no direct coupling between the two.

If I understand your use case correctly, When `onChange` is triggered, you want to know if there are any validation errors and depending on that do something. I think the new function `getValidationErrors` that you create is perfect for this, so you will do something like:

```js
const options: {
  onChange: () => {
    const errors = editor.getValidationErrors()
    if (errors.length === 0) {
      const json = editor.get()
      // do something, like persisting the JSON
    }
  }
}
```

I think there is no need to wait with firing `onChange` until the debounce validation is executed (just keep the old behavior), and instead we can simply trigger not-debounded validation inside `getValidationErrors` if needed, something like:

```js
JSONEditor.prototype.getValidationErrors = function () {
  // run validation directly if still pending
  this._debouncedValidate.flush()

  // return the (up to date) validation errors
  return this.lastSchemaErrors
}
```

What do you think?

**Comment by ChrisAcrobat** [comment]
I can try it, but I think that when I prototype it that the promise that I got back was the previous `getValidationErrors`-promise that was not up to date. But since it was just a prototype it might have ben something else that was wrong.
I'll reply after I have taken a look.

**Comment by ChrisAcrobat** [comment]
I have reverted the changes of 2fa1b50b8e80a7345c296b8920cd1870b93fab88 and 7f006071e3468b06236e66fef218f1de5b7874a3 and, I think, solved the the same issue by storing the promise's resolve callback instead of the promise. But I would like to test it some more before I suggest it to be merged. I'll reply as soon as I have got the time.

**Comment by josdejong** [comment]
@ChrisAcrobat this is a bit more complex than I expected, I forgot that validation can be async, and that the uses `debounce` function is a custom made and not the Lodash one which has this nice `flush()` method.

I also tried to work out a solution, see #1319. Basically I would like to have the existing `.validate()` method return a promise resolving with the errors. What do you think?

**Comment by ChrisAcrobat** [comment]
I haven't had time to fully test my solution yet, but when I do I can test both and say how they work.
But in short, yes it should work if it also is debounced correctly.
I also realised that maybe my solution with just storing the call back maybe isn't that optimal. In theory it might happen that two callbacks executes in the wrong order, making the second one (first to execute) reporting an error and the first (later to execute) reporting no error, resulting in a report that says the second one with error contains no error.

**Comment by josdejong** [comment]
Yes indeed, that makes it complicated with this combination of debouncing _and_ async. Therefore I thought I may be easier to simply "force" running the validation again, independent of the debouncing functionality, to keep things simple and reliable.

**Comment by josdejong** [comment]
Closing this PR in favor of #1319. Thanks again!

**Pull request closed without merging**
