### PR TITLE
onValidationError option

### PR DESCRIPTION
**Pull request by meirotstein**
This PR adds the `onValidationError` option as discussed on #612

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Meir, this works like a charm! I see you created a clear example and wrote docs for the new feature :+1: .

To small feedbacks:

1. The custom onValidate error in the example (`'Member must be an object with properties "name" and "age"'`) did did confuse me, I thought there was an error in the editor. Maybe replace this custom error with something realistic like actually check whether the age is between 18 and 99 or something like that?
2. I understand the function `isValidationErrorChanged`, but I think we could make this a bit more generic: It basically checks whether two objects are equal, right? Can we replace this with say the `isEqual` of lodash? (we're not yet using lodash but there are quite some places where we could use it). Or we could use a simple `JSON.stringify(currErr) === JSON.stringify(prevErr)`. Or are there specific reasons we cannot simply compare the two arrays as a whole?

**Comment by meirotstein** [comment]
**Custom validation example**: you are right - a bad copy of another example :grimacing: - will be fixed.
**`isValidationErrorChanged` implementation**: two reasons:
1. I first tried the `JSON.stringify` solution but it didn't work, I guess there were minor changes between the error objects that I cannot explain, anyway I didn't get deep into it because of the 2nd reason:
2. I feel a bit uncomfortable with `stringify` because I'm afraid that on very big documents with many errors it can get quite heavy (serialization + comparison).
The current approach is more gradual, and if there's a difference somewhere in the middle it will not have to go over the entire arrays.
I didn't try the `lodash` simply because this lib doesn't have this dependency - there's a usage of it on the React examples, but not on the main bundle. I really like `lodash` and use it on many other projects and for sure will try this option if it's available.

**Comment by josdejong** [comment]
I think you're right that with larger objects and many errors stringify will probably not perform well (though that's an assumption ;) ). 

I think your current solution is fine, just looking if we can simplify it somehow. We can just add `lodash` to the project if that helps us, but if stringify doesn't work, the lodash `isEqual` will probably also not work? Would be nice if you can give the `isEqual` approach a short try and if it doesn't work out we can just keep the current solution.

**Comment by meirotstein** [comment]
@josdejong I will give it a try

**Comment by meirotstein** [comment]
I have tested it - it will not work 😄 from the  same reason that `stringify` is not working:
The validation error object also contains the changed value - that makes the previous and current object always differ.

**Comment by josdejong** [comment]
Ahh, of course, that makes sense :smile: . So then it would only work with a customized comparator, which is what you've already built with `isValidationErrorChanged`.

Thanks for updating the example. Will merge now

**Comment by josdejong** [comment]
`onValidationError` is now available in `v7.4.0`, thanks again!

**Pull request merged**
