### PR TITLE
for #763

### PR DESCRIPTION
**Pull request by Thaina**
#763

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for this fix @Thaina . Can you please change the indentation to 2 space?

**Comment by Thaina** [comment]
@josdejong Right now in workplace I don't have access to the repo and ssh key from my home machine. Couldn't you just pull and change it? Or actually you could just copied mine and push in your repo then drop this pull request. I just want this to be fixed

**Comment by josdejong** [comment]
Yes will do, thanks for your quick reply.

I will also do some deeper digging, I'm not sure whether this solves the cause, maybe node should not be undefined.

**Comment by Thaina** [comment]
@josdejong I have dig the code and see that `node` are `undefined` because the dropdown menu for insert/delete the node is not a node itself yet when it clicked it still invoke the autocomplete

The actual fix might be that, the dropdown menu should not invoke autoComplete. because it cannot typing anything there

**Comment by josdejong** [comment]
yes indeed. I've added an extra check before calling `_showAutoComplete`, now and also made itself `_showAutoComplete` robust against missing node (like your PR).

**Pull request closed without merging**
