### PR TITLE
Basic translate

### PR DESCRIPTION
**Pull request by mariohmol**
Hi there.. awesome module.. thank you!

I'm using this and needed to have in my language, so i did this changes.. if you think this can be useful.. feel free to merge!

bests

### CODE REVIEW

**Comment by josdejong** [comment]
wow, this is awesome @mariohmol , looks good!

I think to make this complete, we could implement an option `lang` (which defaults to `navigator.language`), and implement a way to pass additional translations into JSONEditor without having to hack the source code, for example via a new option `locales: {...}`. Would you be interested to implement these options?

**Comment by mariohmol** [comment]
Nowdays its getting the default lang by navigator language, but the translations are indeed in the source code. I will make this paremeter now to include more locales as a parameter

**Comment by josdejong** [comment]
Cool, thanks! 

I think using `navigator.language` as default is a great solution, but there should be an option to force usage of a specific language too (ie. an option `lang`). Some applications couple a language to a user profile rather than a machine. And some sites may only support English and want to force that in all used components in order to have a consistent site. What do you think?

**Comment by mariohmol** [comment]
I included in this PR, 2 options:

*  `languages` to insert or override translations keys 
* `language` property to force a language.

**Comment by mariohmol** [comment]
Did a small improvement... guess now is everything good to go

**Comment by mariohmol** [comment]
Added the language support on angular component 

https://github.com/mariohmol/ang-jsoneditor/commit/68877f0c3b7ae6648d89b4c57521fffe786f5de8

**Comment by josdejong** [comment]
Looks great, thanks for updating the docs and adding an example!

After merging I will refactor your code to ES5, there isn't yet a transpiler in the project setup to convert to ES5.

**Comment by josdejong** [comment]
@mariohmol your translation solution is now available in `v5.14.0`, thanks again.

**Comment by mariohmol** [comment]
Thanks! I upgraded the ang component to this version and did the demo with buttons where can change language to test.

https://raw.githubusercontent.com/mariohmol/ang-jsoneditor/master/src/assets/printDemo.png

**Pull request merged**
