### PR TITLE
Adds ability to hide sort and transform options

### LINKED ISSUE #580: Hide the Sort and Transform buttons
In [version 5.19.0](https://github.com/josdejong/jsoneditor/blob/master/HISTORY.md#2018-07-11-version-5190), sort and transform options were added. While these are really cool options, I would like to hide them from users to keep the interface simple.

Are there plans to allow hiding the sort/transform buttons via the options object?

Thanks for your time and the awesome module!

### PR DESCRIPTION
**Pull request by tanmayrajani**
Closes #580

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @tanmayrajani , I will review your PR coming weekend.

**Comment by josdejong** [comment]
Sorry for the delay @tanmayrajani, I had some busy weeks.

Your PR looks nice and simple, thanks! And happy to see you updated the docs accordingly :)

A few feedback points:

1. I think we should also disable the sort and transform buttons in the context menu (available when you click the action button left from an Object or Array), see method `Node.showContextMenu`.
2. I'm thinking about the naming of these two options (`hideSort` and `hideTransform`). I generally try to avoid negations in options. And I think we should try to be a bit consistent with similar (boolean) options like `history`, `search`, `navigationBar`, `statusBar`, and `colorPicker`. How about naming the new options `sort` and `transform` (most consistent with the existing options), or `enableSort` and `enableTransform` (maybe most clear)? What do you think?

**Comment by tanmayrajani** [comment]
I went with `enableSort` and `enableTransform` but after the commit, I now feel like they're better off being consistent with other options. 

Also, I was a bit skeptical about "Ability to display the Sort option" wordings. Any other suggestions there?

**Comment by josdejong** [comment]
:+1: thanks @tanmayrajani

**Comment by pedro-j-morais-alb** [comment]
hi. someone knows how to hide Repair JSON button in Code mode? enableRepair = false isnt working for me. thx

**Comment by josdejong** [comment]
There is no option to disable the repair button, but you can hide it using CSS.

**Pull request merged**
