### PR TITLE
fix childSchema can not access $ref and add title to display the schema description

### PR DESCRIPTION
**Pull request by tylerchen**
fix childSchema can not access $ref and add title to display the schema description

### CODE REVIEW

**Comment by josdejong** [comment]
ow sorry I was confused with your different PR's, I've now merged #624, but it has the same code changes as this PR, right?

**Comment by tylerchen** [comment]
Right, I am sorry about that because of the last commit create the new pr and I confused those prs.

**Comment by josdejong** [comment]
No problem :+1:

**Comment by josdejong** [comment]
Your fix is now available in `v5.27.1`

**Pull request closed without merging**
