### PR TITLE
Add option to sort objects keys alphabetically

### PR DESCRIPTION
**Pull request by edufelipe**
The new option is disabled by default, but when enabled makes editing large documents in tree or form mode much easier.

It also includes the nicety of being a natural sort, so object that have numbers inside strings as keys sort very well.

### CODE REVIEW

**Comment by josdejong** [comment]
That's a nice idea. Thanks for your implementation including docs and everything, it looks neat!

**Comment by josdejong** [comment]
@edufelipe I applied natural sorting to the sorting via the context menu too for consistency. I needed a comparator function `naturalSort(a, b)` for this though instead of the `naturalSort(array)` method that you provided, I included the [javascript-natural-sort](https://www.npmjs.com/package/javascript-natural-sort) library for this to save me the work of reinventing the wheel. See: https://github.com/josdejong/jsoneditor/commit/e7b7362fc2cd10ad3be78dee805b831b497cb9df

**Comment by edufelipe** [comment]
@josdejong You know what's funny? I knew about that library and did not use it on purpose, mainly because your project is not heavy on dependencies and `left-pad` just happened. I was sure you would reject my pull request if I included another library. Oh well, that's what I get for not asking about it first. 😄

**Comment by josdejong** [comment]
ha ha :)

I guess you agree with the current approach?

**Comment by edufelipe** [comment]
Sure! As long as there is an option to do it programmatically on JSON load, everything works for me.

**Pull request merged**
