### PR TITLE
Changing sass variables #881

### PR DESCRIPTION
**Pull request by petermanders89**
Pull request for implementing #881

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Peter! 

Small question: you've added `!default` to most of the variables but not all. Is there a specific reason not to add `!default` to `$jse-box-shadow...` and `$js2-font...` variables?

**Comment by petermanders89** [comment]
Good question indeed!

I was aiming to focus on the colors, but indeed why not add it to all variables it to all variables. I also took the liberty to add an icons variable. I got carried away a bit while browsing threw the sass files. It might be that people want to customize the images or overwrite the path of the file considering there build system.

**Comment by josdejong** [comment]
Nice idea to create a variable for the icons too! I think it's good that _everything_ is now consistently `!default`. Thanks!

**Comment by josdejong** [comment]
Available now in `v8.2.0`

**Pull request merged**
