### PR TITLE
Search Box improvements

### PR DESCRIPTION
**Pull request by ppetkow**
**Important to know
This changes is need from previous PR** 

Change html structure of search box; Migration from table to div 
Optimize css

### CODE REVIEW

**Comment by josdejong** [comment]
@ppetkow thanks! 

I've just merged your previous PR, and there are merge conflicts now. Can you have a look at that? It's best not to commit changes in `dist/*` (that's only needed right before publishing. It's annoying - a leftover requirement for bower.io, `dist` will be removed from the repo in the first next breaking version).

**Comment by ppetkow** [comment]
Done

**Comment by josdejong** [comment]
@ppetkow I've reviewed and tested your PR, all looks good! 

One small thing: can you clean up the old, commented code like 
`//td = document.createElement('td');`?

**Comment by ppetkow** [comment]
Done :) After merge you can close the ticket dont ask :)

**Comment by josdejong** [comment]
Thanks :+1:

**Pull request merged**
