### PR TITLE
add support for json schema references ($ref)

### PR DESCRIPTION
**Pull request by meirotstein**
Add support for JSON schema validation for schemas which has references to other schemas using the '$ref' option.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Meir for your PR! I will look into it coming Friday or Saturday.

**Comment by josdejong** [comment]
Thanks again, your code looks neat @meirotstein ! This is a nice new feature. Just for reference: this PR solves #302.

One thought: instead of a new method `setSchemaRef`, we could simply pass the schema refs as an optional second argument of the existing method `setSchema`, like `setSchema(schema [, schemaRefs])`. The `schemaRefs` argument would be exactly the same as the new option `schemaRefs` (an object with ref as key, schema as value), and this way both schema and refs are applied in a single action instead of two consecutive actions. What do you think?

**Comment by meirotstein** [comment]
Hi - thanks for the feedback!

I agree - your suggestion is much more cleaner then adding a new method - I will push an update later on today.

**Comment by josdejong** [comment]
Thanks!

**Comment by josdejong** [comment]
Looks good, thanks again @meirotstein !

**Comment by josdejong** [comment]
JSON schema refs is now available in `v5.9.0` :tada:

**Comment by meirotstein** [comment]
Awesome!
Thank you very much!

**Pull request merged**
