### PR TITLE
Add listeners to list (shadow) root instead of window,

### PR DESCRIPTION
**Pull request by tomalec**
make context menus work in Shadow DOM.

Fixes https://github.com/josdejong/jsoneditor/issues/447

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for this fix @tomalec ! 

I think there is one more occurrence of `window`, in `ContextMenu.prototype.hide` where the event listeners are cleaned up again. I think that should be adjusted too.

**Comment by tomalec** [comment]
Thanks for the review.
Is it better now?

**Comment by josdejong** [comment]
Looks good, thanks for updating!

**Comment by josdejong** [comment]
Your fix is now available in `v5.9.4`

**Comment by tomalec** [comment]
Great! Thanks a lot!

**Comment by josdejong** [comment]
@tomalec it turns out that your solution didn't work out exactly as we expected, and the global listeners where never cleaned up again causing the editor not responding to mouse clicks anymore after using the context menu once. I've fixed this in `v5.9.5` (see https://github.com/josdejong/jsoneditor/commit/d5ba54890265ca5d89e3d85404f92f5df1ab5619), can you please check whether the fix still works for shadow DOM too?

**Comment by tomalec** [comment]
Thanks it works fine! Sorry for missing that out :|

BTW, Just to note, there is no 5.9.5 tag yet at https://github.com/josdejong/jsoneditor/releases

**Comment by josdejong** [comment]
:thumbsup: I had missed it to. 

I've also created the `v5.9.5`, I had completely forgotten that.

**Pull request merged**
