### PR TITLE
Added save dialog to example 4

### PR DESCRIPTION
**Pull request by RDCH106**
Added dialog asking for the file name to save it

### CODE REVIEW

**Comment by josdejong** [comment]
Nice improvement, thanks Ruben.

Two little things:
- can you please redo your PR to the `develop` branch instead? I can't accept it on `master`
- I'm not sure if it's needed to take special care for a `.json` suffix in the file name: if people want to name there file myDocumet.txt or whatever that's fine I guess, and this extra code distracts from the key point of the example. What do you think?

**Comment by RDCH106** [comment]
- No problem. I will create a pull request to develop branch.

- The extensions are orientative. Usually the extensions in the operative systems are to asign an icon and default program. I think that it has not sense to create a standard json file with different extension to json. Not include extension is an other option, but it is more informative with the extension. About the clearity of the code, the code includes comments and the save option is full functionally. Ready to use! In my opinion is better than without extension checking.

Have I your aprovement to create a new PR in develop?

**Comment by josdejong** [comment]
Ok thanks for your feedback. Let's keep the extension handling code in, it's fine with me. I will await your PR on develop.

**Comment by RDCH106** [comment]
OK

**Comment by josdejong** [comment]
I will close this PR now in favor of #305

**Pull request closed without merging**
