### PR TITLE
Fix Node._findSchema()

### PR DESCRIPTION
**Pull request by AdamVig**
The static method `Node._findSchema()` returns incorrect results sometimes. I added some tests that exercise the method to show the situations it fails in, and will hopefully be able to fix the method early next week.

### CODE REVIEW

**Comment by AdamVig** [comment]
@josdejong I wouldn't merge this yet because the tests are failing. I will push further commits on this branch to fix the broken method.

**Comment by josdejong** [comment]
Thanks @AdamVig for diving into this! I guess `jsdom` will be a devDepencency?

**Comment by AdamVig** [comment]
@josdejong You are welcome. Yes, `jsdom` will be a dev dependency.

**Comment by AdamVig** [comment]
@josdejong Ready for review.

**Comment by josdejong** [comment]
Thanks, will do testing and review coming weekend. So I guess you found the issue making `_findSchema` not work correctly in all cases?

**Comment by AdamVig** [comment]
@josdejong Thanks, sounds good.

Yeah, I found and fixed two issues:
1. With a property whose schema was in `patternProperties`, the function would always return the schema defined last in the `patternProperties` object. This was fixed by checking if the current property matches any of the regular expressions defined in the `patternProperties` object and returning the schema if the property matches.
2. With a schema that has both `properties` and `patternProperties`, a schema from within `patternProperties` would be returned sometimes for a property whose schema was in `properties`. This was fixed by adding a check to the `patternProperties` conditional.

**Comment by josdejong** [comment]
wow, that's great!

**Comment by AdamVig** [comment]
It is definitely possible that in fixing these two issues I may have created new issues, but since there are no pre-existing automated tests it is difficult to tell. I tested the library from this branch in an internal application at my company and it fixed the bug I was seeing, and seemed to work correctly otherwise, but I didn't conduct an in-depth test.

It might be better in the future to replace the `Node._findSchema` method with an external library that has its own suite of unit tests, because walking JSON schema accurately is difficult and prone to bugs. I found two options: [`json-schema-traverse`](https://github.com/epoberezkin/json-schema-traverse/) by the `ajv` guy and [`json-schema-walker`](https://github.com/cloudflare/json-schema-tools/tree/master/workspaces/json-schema-walker) by Cloudflare. Both are focused on traversal rather than finding subschemas, but it might be relatively easy to repurpose either of them to work for finding subschemas.

**Comment by josdejong** [comment]
Thanks again starting to create unit tests, the library hardly has any unit tests, this helps a lot.

It would indeed be a good step see whether we can use an external library for all the JSON Schema related logic (like we do use Ajv instead of reinventing the wheel).

**Comment by josdejong** [comment]
@AdamVig your fixes are now available in `v5.29.0`

**Pull request merged**
