### PR TITLE
Don't package CONTRIBUTING.md or examples folder

### PR DESCRIPTION
**Pull request by MarkHerhold**
If you don't want this, please just close.

Thanks for the awesome module!

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks Mark, I think CONTRIBUTING is indeed not needed in the package. Examples on the other hand are very relevant I think.

**Comment by MarkHerhold** [comment]
I always look at it from the other perspective of a package being downloaded tens of thousands of times by CI servers for deployments. Less is sometimes more. At any rate, I'll make the change.

**Comment by josdejong** [comment]
Yes it's good to try make packages as small as possible. For me optimizing for the user comes first, and machines come second. That means having docs and examples at your disposal everywhere :).

I prefer leaving the `examples` in, but `CONTRIBUTING.md` can be removed, that has no value in the context of a published package.

**Comment by josdejong** [comment]
Thanks for the update Mark.

**Pull request merged**
