### PR TITLE
Fix schema not found if using internal references

### PR DESCRIPTION
**Pull request by maufl**
This merge request fixes issue #1158 
I refactored the `Node._findSchema` method, which now should correctly resolve internal references. I also added a test case for this.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks a lot for this fix Felix. Your refactoring looks very neat. And I like it to see more `const` 😉 .

One question: in the old version there was an iteration:
```js
for (let i = 0; i < path.length && childSchema; i++) {
  // ...
}
```
This iteration seems gone now, did you replace it by a recursive solution or something? Or was it redundant code?

**Comment by maufl** [comment]
> This iteration seems gone now, did you replace it by a recursive solution or something? Or was it redundant code?

Yes, the old code used both an iteration with a for loop and one with a recursive call. I don't know why, to me it seemed to be redundant. The new code only does the recursive iteration. As it did not break any tests, I assume that it really was unnecessary duplication.

**Comment by josdejong** [comment]
Wow, that is a very nice simplification then. This function is one of the few things that is well tested in the library, so all should be good indeed. I've also checked whether the JSON Schema examples still work, and all looks good to go 👍 .

**Comment by josdejong** [comment]
Fix is now published in `v9.1.3`, thanks again Felix

**Pull request merged**
