### PR TITLE
Show examples from schema in field tooltips

### PR DESCRIPTION
**Pull request by AdamVig**
image

### CODE REVIEW

**Comment by AdamVig** [comment]
@josdejong I'm not sure if you get notified about pull requests, so I am tagging you here as well. Let me know if this is redundant; I don't want to spam you. 😄

**Comment by josdejong** [comment]
Thanks Adam, looks good on first sight, thanks for taking the time to even do all translations :)

I will review+test in more detail tomorrow or the day after.

I do get notified on every PR and issue. An extra message in a PR doesn't cause extra spam on my side, it's just one email thread in my mailbox, so no problem at all.

**Comment by josdejong** [comment]
I've done some testing, all works like a charm. Thanks again @AdamVig!

**Comment by josdejong** [comment]
Available now in `v5.31.0`

**Pull request merged**
